<a href="https://colab.research.google.com/github/anh-honcharuk/Neural-Networks/blob/main/4_lec_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

training_inputs = np.array([[0, 0, 1],
                           [1, 1, 1],
                           [1, 0, 1],
                           [0, 1, 1]])
training_outputs = np.array([[0, 1, 1, 0]]).T

np.random.seed(1)

synaptic_weights = 2 * np.random.random((3, 1)) - 1

print("Rand init weights:")
print(synaptic_weights)

for i in range(20000):
    input_layer = training_inputs
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))

    err = training_outputs - outputs
    adjustments = np.dot(input_layer.T, err * (outputs * (1 - outputs)))

    synaptic_weights += adjustments

print("weights after lerning:")
print(synaptic_weights)

print("result:")
print(outputs)

# new
new_inputs = np.array([1, 1, 0])
outputs = sigmoid(np.dot(new_inputs, synaptic_weights))

print("new:")
print(outputs)

Rand init weights:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
weights after lerning:
[[10.38040701]
 [-0.20641179]
 [-4.98452047]]
result:
[[0.00679672]
 [0.99445583]
 [0.99548516]
 [0.00553614]]
new:
[0.99996185]
